version: "2"
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.43.0
    restart: unless-stopped
    ports:
      - "9050:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
      - '--web.enable-remote-write-receiver'
    networks:
      - local-net
      
  grafana:
    image: grafana/grafana:9.2.15
    container_name: grafana
    volumes:
      # - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana:/etc/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - local-net

networks:
  local-net:
